#
# Copyright (c) 2020, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
#

# Configuration for probot-no-response - https://github.com/probot/no-response

daysUntilClose: 7
responseRequiredLabel: 'more information required'
closeComment: >
  This issue has been automatically closed because there has been no response
  to our request for more information from the original author. Currently, there
  is not enough information provided for us to take action. Please reply and 
  reopen this issue if you need additional assistance.
