#
# Copyright (c) 2021, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
#

name: "validate-updated-issue"
on:
  issues:
    types: [edited]
  issue_comment:
    types: [created, edited]

jobs:
  validate-issue:
    # Has label: 'more information needed'
    # Does NOT have labels:
    # - 'validated'
    # - 'investigating'
    # - 'feature'
    # - 'owned by another team'
    # - 'bug'
    if: contains(github.event.issue.labels.*.name, 'more information needed') && !contains(github.event.issue.labels.*.name, 'validated') && !contains(github.event.issue.labels.*.name, 'investigating') && !contains(github.event.issue.labels.*.name, 'feature') && !contains(github.event.issue.labels.*.name, 'owned by another team') && !contains(github.event.issue.labels.*.name, 'bug')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn install
      - name: Validate issue
        id: validate-issue
        uses: ./.github/actions/validate-issue
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN}}
