name: "new-issue"
on:
  issues:
    types: [opened, edited]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
  missed-info:
    runs-on: ubuntu-latest
    steps:
      - name: Missed Steps to reproduce
        if: contains(github.event.issue.body, 'Steps to reproduce') == false
        env:
          STEPS_REPRODUCE: Steps to reproduce
        run: echo "$STEPS_REPRODUCE"
      - name: Missed Link to a GitHub repository
        if: contains(github.event.issue.body, 'Link to a GitHub repository') == false
        env:
          LINK_TO_GITHUB: Link to a GitHub repository
        run: echo "$LINK_TO_GITHUB"
      - name: Missed Expected result
        if: contains(github.event.issue.body, 'Expected result') == false
        env:
          EXPECTED_RESULT: Expected result
        run: echo "$EXPECTED_RESULT"
      - name: Missed Actual result
        if: contains(github.event.issue.body, 'Actual result') == false
        env:
          ACTUAL_RESULT: Actual result
        run: echo "$ACTUAL_RESULT"
      - name: Missed CLI version
        if: contains(github.event.issue.body, 'CLI version') == false
        env:
          CLI_VERSION: CLI version
        run: echo "$CLI_VERSION"
      - name: Missed plugin version
        if: contains(github.event.issue.body, 'plugin version') == false
        env:
          PLUGIN_VERSION: Plugin version
        run: echo "$PLUGIN_VERSION"
      - name: Missed OS version
        if: contains(github.event.issue.body, 'OS') == false
        env:
          OS_VERSION: OS version
        run: echo "$OS_VERSION"
  more-info-required:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0 
    - name: issue comment
      id: issue_comment
      uses: ./
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN}}
        label: 'more information required'
        message: >
          This issue is missing the following required information: 
          $STEPS_REPRODUCE
          $LINK_TO_GITHUB
          $EXPECTED_RESULT
          $ACTUAL_RESULT
          $CLI_VERSION
          $PLUGIN_VERSION
          $OS_VERSION
          When you provide us this information we'll triage and reproduce the issue. 
    - name: log action output
      run: echo ${{steps.run_action.outputs.message}}
  default-comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0 
    - name: issue comment
      id: issue_comment
      uses: ./
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN}}
        message: >
          Thank you for filing this issue.  We appreciate your feedback and will review the issue as soon as possible. 
          Remember, however, that GitHub isn't a mechanism for receiving support under any agreement or SLA. 
          If you require immediate assistance, contact Salesforce Customer Support.
    - name: log action output
      if: contains(github.event.issue.labels.*.name, 'more information required') == false
      run: echo ${{steps.run_action.outputs.message}}
