#
# Copyright (c) 2020, salesforce.com, inc.
# All rights reserved.
# Licensed under the BSD 3-Clause license.
# For full license text, see LICENSE.txt file in the repo root or https://opensource.org/licenses/BSD-3-Clause
#

name: "new-issue"
on: # any issue opened
  issues:
    types: [opened]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
  missed-info:
    runs-on: ubuntu-latest
    needs: [triage]
    outputs:
      STEPS_REPRODUCE: ${{ steps.steps_to_reproduce.outputs.STEPS_REPRODUCE }}
      LINK_TO_GITHUB: ${{ steps.link_to_github.outputs.LINK_TO_GITHUB }}
      EXPECTED_RESULT: ${{ steps.expected_result.outputs.EXPECTED_RESULT }}
      ACTUAL_RESULT: ${{ steps.actual_result.outputs.ACTUAL_RESULT }}
      CLI_VERSION: ${{ steps.missed_cli_version.outputs.CLI_VERSION }}
      PLUGIN_VERSION: ${{ steps.missed_plugin_version.outputs.PLUGIN_VERSION }}
      OS_VERSION: ${{ steps.missed_os_version.outputs.OS_VERSION }}
    steps:
      - uses: actions/checkout@v2.0.0 
      - name: Missed Steps to reproduce
        id: steps_to_reproduce
        if: ${{contains(github.event.issue.body, 'Steps To Reproduce') == false}}
        env:
          STEPS_REPRODUCE: Steps to reproduce
        run: echo "::set-output name=STEPS_REPRODUCE::$STEPS_REPRODUCE"
      - name: Missed Link to a GitHub repository
        id: link_to_github
        if: contains(github.event.issue.body, 'Repository to reproduce') == false
        env:
          LINK_TO_GITHUB: Link to a GitHub repository
        run: echo "::set-output name=LINK_TO_GITHUB::$LINK_TO_GITHUB"
      - name: Missed Expected result
        id: expected_result
        if: contains(github.event.issue.body, 'Expected result') == false
        env:
          EXPECTED_RESULT: Expected result
        run: echo "::set-output name=EXPECTED_RESULT::$EXPECTED_RESULT"
      - name: Missed Actual result
        id: actual_result
        if: contains(github.event.issue.body, 'Actual result') == false
        env:
          ACTUAL_RESULT: Actual result
        run: echo "::set-output name=ACTUAL_RESULT::$ACTUAL_RESULT"
      - name: Missed CLI version
        id: missed_cli_version
        if: contains(github.event.issue.body, 'CLI Version') == false
        env:
          CLI_VERSION: CLI version
        run: echo "::set-output name=CLI_VERSION::$CLI_VERSION"
      - name: Missed plugin version
        id: missed_plugin_version
        if: contains(github.event.issue.body, 'plugin Version') == false
        env:
          PLUGIN_VERSION: Plugin version
        run: echo "::set-output name=PLUGIN_VERSION::$PLUGIN_VERSION"
      - name: Missed OS version
        id: missed_os_version
        if: contains(github.event.issue.body, 'OS') == false
        env:
          OS_VERSION: OS version
        run: echo "::set-output name=OS_VERSION::$OS_VERSION"
  display-message:
    runs-on: ubuntu-latest
    needs: [triage, missed-info]
    steps:
      - uses: actions/checkout@v2.0.0 
      - name: issue comment
        if: ${{needs.missed-info.outputs.STEPS_REPRODUCE != '' 
          || needs.missed-info.outputs.LINK_TO_GITHUB != ''
          || needs.missed-info.outputs.EXPECTED_RESULT != ''
          || needs.missed-info.outputs.ACTUAL_RESULT != ''
          || needs.missed-info.outputs.CLI_VERSION != ''
          || needs.missed-info.outputs.PLUGIN_VERSION != ''
          || needs.missed-info.outputs.OS_VERSION != ''}}
        id: issue_comment_missing
        uses: ./
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN}}
          message: >
            ${{format('{{Your issue is missing this required information: {0} {1} {2} {3} {4} {5} {6}. When you provide us this information we''ll triage and reproduce the issue.}}',
            needs.missed-info.outputs.STEPS_REPRODUCE, needs.missed-info.outputs.LINK_TO_GITHUB, needs.missed-info.outputs.EXPECTED_RESULT, needs.missed-info.outputs.ACTUAL_RESULT,
            needs.missed-info.outputs.CLI_VERSION, needs.missed-info.outputs.PLUGIN_VERSION, needs.missed-info.outputs.OS_VERSION)}}
      - name: issue comment
        if: ${{needs.missed-info.outputs.STEPS_REPRODUCE == '' 
          && needs.missed-info.outputs.LINK_TO_GITHUB == ''
          && needs.missed-info.outputs.EXPECTED_RESULT == ''
          && needs.missed-info.outputs.ACTUAL_RESULT == ''
          && needs.missed-info.outputs.CLI_VERSION == ''
          && needs.missed-info.outputs.PLUGIN_VERSION == ''
          && needs.missed-info.outputs.OS_VERSION == ''}}
        id: issue_comment
        uses: ./
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN}}
          message: >
            Thank you for filing this issue.  We appreciate your feedback and will review the issue as soon as possible. 
            Remember, however, that GitHub isn't a mechanism for receiving support under any agreement or SLA. 
            If you require immediate assistance, contact Salesforce Customer Support.
      - name: log action output
        run: echo ${{steps.run_action.outputs.message}}